
import React, { useState, useCallback } from 'react';
import InfiniteCanvas from '@/components/InfiniteCanvas';
import AIInterface from '@/components/AIInterface';

const Index = () => {
  const [generatedObjects, setGeneratedObjects] = useState<any[]>([]);
  const [uiComponents, setUIComponents] = useState<string[]>([]);

  const handleObjectGenerated = useCallback((code: string, metadata: any) => {
    console.log('Object generated by AI:', { code, metadata });
    // In a real implementation, this would compile and add the object to the canvas
    setGeneratedObjects(prev => [...prev, { code, metadata, id: Date.now() }]);
  }, []);

  const handleCodeModified = useCallback((code: string) => {
    console.log('Code modified by AI:', code);
    // This would apply code modifications to existing objects
  }, []);

  const handleUIUpdated = useCallback((code: string) => {
    console.log('UI updated by AI:', code);
    // This would dynamically update the UI
    setUIComponents(prev => [...prev, code]);
  }, []);

  return (
    <div className="relative w-full h-screen overflow-hidden">
      {/* Main 3D Canvas */}
      <InfiniteCanvas />
      
      {/* AI Interface */}
      <AIInterface
        onObjectGenerated={handleObjectGenerated}
        onCodeModified={handleCodeModified}
        onUIUpdated={handleUIUpdated}
      />

      {/* Dynamic UI Components rendered by AI */}
      {uiComponents.length > 0 && (
        <div className="fixed top-4 left-1/2 transform -translate-x-1/2 z-50">
          <div className="bg-black/80 backdrop-blur-sm border border-purple-500/30 rounded-lg p-4">
            <h3 className="text-purple-400 text-sm font-semibold mb-2">AI Generated UI</h3>
            <div className="text-xs text-gray-400">
              {uiComponents.length} component(s) generated
            </div>
          </div>
        </div>
      )}

      {/* Debug Info */}
      <div className="fixed bottom-20 left-4 z-50 text-xs text-gray-500 space-y-1">
        <div>Generated Objects: {generatedObjects.length}</div>
        <div>UI Components: {uiComponents.length}</div>
        <div className="text-cyan-400">AI Canvas v1.0 - Self-Evolving</div>
      </div>
    </div>
  );
};

export default Index;
