
import React, { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Brain, Code, Palette, Zap, Key, AlertCircle } from 'lucide-react';
import aiService, { AIGenerationResponse } from '@/services/aiService';
import { toast } from 'sonner';

interface AIInterfaceProps {
  onObjectGenerated: (code: string, metadata: any) => void;
  onCodeModified: (code: string) => void;
  onUIUpdated: (code: string) => void;
}

export default function AIInterface({ 
  onObjectGenerated, 
  onCodeModified, 
  onUIUpdated 
}: AIInterfaceProps) {
  const [prompt, setPrompt] = useState('');
  const [apiKey, setApiKey] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [lastResponse, setLastResponse] = useState<AIGenerationResponse | null>(null);
  const [hasApiKey, setHasApiKey] = useState(false);

  useEffect(() => {
    const savedKey = aiService.getApiKey();
    if (savedKey) {
      setApiKey(savedKey);
      setHasApiKey(true);
    }
  }, []);

  const handleApiKeySubmit = () => {
    if (apiKey.trim()) {
      aiService.setApiKey(apiKey.trim());
      setHasApiKey(true);
      toast.success('xAI API key saved successfully!');
    } else {
      toast.error('Please enter a valid API key');
    }
  };

  const handleGenerate = async (type: 'object' | 'code' | 'ui' | 'self-modify') => {
    if (!hasApiKey) {
      toast.error('Please enter your xAI API key first');
      return;
    }

    if (!prompt.trim() && type !== 'self-modify') {
      toast.error('Please enter a prompt');
      return;
    }
    
    setIsGenerating(true);
    try {
      let response: AIGenerationResponse;
      
      switch (type) {
        case 'object':
          response = await aiService.generateObject(prompt);
          if (response.success && response.code) {
            onObjectGenerated(response.code, response.metadata);
            toast.success('3D Object generated by Grok!');
          }
          break;
        case 'code':
          response = await aiService.modifyCode('', prompt);
          if (response.success && response.code) {
            onCodeModified(response.code);
            toast.success('Code modified by Grok!');
          }
          break;
        case 'ui':
          response = await aiService.generateUI(prompt);
          if (response.success && response.code) {
            onUIUpdated(response.code);
            toast.success('UI generated by Grok!');
          }
          break;
        case 'self-modify':
          response = await aiService.improveSelf();
          toast.success('Grok analyzed the system!');
          break;
        default:
          return;
      }
      
      if (!response.success) {
        toast.error(response.error || 'Generation failed');
      }
      
      setLastResponse(response);
      setPrompt('');
    } catch (error) {
      console.error('AI generation failed:', error);
      toast.error('Failed to connect to xAI API. Check your API key.');
    } finally {
      setIsGenerating(false);
    }
  };

  if (!hasApiKey) {
    return (
      <div className="fixed left-4 top-1/2 transform -translate-y-1/2 z-40 w-80">
        <Card className="bg-black/90 backdrop-blur-sm border-cyan-500/30">
          <CardHeader>
            <CardTitle className="text-cyan-400 flex items-center gap-2">
              <Key className="w-5 h-5" />
              xAI API Setup
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="flex items-start gap-2 p-3 bg-yellow-500/10 border border-yellow-500/30 rounded-lg">
              <AlertCircle className="w-4 h-4 text-yellow-400 mt-0.5 flex-shrink-0" />
              <div className="text-xs text-yellow-300">
                Get your API key from{' '}
                <a 
                  href="https://console.x.ai/" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="underline hover:text-yellow-200"
                >
                  console.x.ai
                </a>
              </div>
            </div>
            <div>
              <label className="text-sm text-gray-400 mb-2 block">Enter your xAI API Key</label>
              <Input
                type="password"
                placeholder="xai-..."
                value={apiKey}
                onChange={(e) => setApiKey(e.target.value)}
                className="bg-gray-800 border-gray-600 text-white"
              />
            </div>
            <Button
              onClick={handleApiKeySubmit}
              className="w-full bg-cyan-500 hover:bg-cyan-600 text-black"
            >
              Connect to Grok-3-Beta
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="fixed left-4 top-1/2 transform -translate-y-1/2 z-40 w-80">
      <Card className="bg-black/90 backdrop-blur-sm border-cyan-500/30">
        <CardHeader>
          <CardTitle className="text-cyan-400 flex items-center gap-2">
            <Brain className="w-5 h-5" />
            Grok-3-Beta Control
          </CardTitle>
          <div className="text-xs text-green-400">✓ Connected to xAI</div>
        </CardHeader>
        <CardContent>
          <Tabs defaultValue="generate" className="w-full">
            <TabsList className="grid w-full grid-cols-4 bg-gray-800">
              <TabsTrigger value="generate" className="text-xs">
                <Code className="w-4 h-4" />
              </TabsTrigger>
              <TabsTrigger value="ui" className="text-xs">
                <Palette className="w-4 h-4" />
              </TabsTrigger>
              <TabsTrigger value="modify" className="text-xs">
                <Zap className="w-4 h-4" />
              </TabsTrigger>
              <TabsTrigger value="self" className="text-xs">
                <Brain className="w-4 h-4" />
              </TabsTrigger>
            </TabsList>
            
            <TabsContent value="generate" className="space-y-3">
              <div>
                <label className="text-sm text-gray-400 mb-2 block">Generate 3D Object</label>
                <Textarea
                  placeholder="A spinning golden cube with particle effects..."
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  className="bg-gray-800 border-gray-600 text-white"
                  rows={3}
                />
                <Button
                  onClick={() => handleGenerate('object')}
                  disabled={isGenerating}
                  className="w-full mt-2 bg-cyan-500 hover:bg-cyan-600 text-black"
                >
                  {isGenerating ? 'Grok Thinking...' : 'Generate with Grok'}
                </Button>
              </div>
            </TabsContent>
            
            <TabsContent value="ui" className="space-y-3">
              <div>
                <label className="text-sm text-gray-400 mb-2 block">Generate UI Component</label>
                <Textarea
                  placeholder="A futuristic control panel with neon buttons..."
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  className="bg-gray-800 border-gray-600 text-white"
                  rows={3}
                />
                <Button
                  onClick={() => handleGenerate('ui')}
                  disabled={isGenerating}
                  className="w-full mt-2 bg-purple-500 hover:bg-purple-600 text-white"
                >
                  {isGenerating ? 'Grok Creating...' : 'Create UI'}
                </Button>
              </div>
            </TabsContent>
            
            <TabsContent value="modify" className="space-y-3">
              <div>
                <label className="text-sm text-gray-400 mb-2 block">Modify System</label>
                <Textarea
                  placeholder="Add physics simulation to all objects..."
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  className="bg-gray-800 border-gray-600 text-white"
                  rows={3}
                />
                <Button
                  onClick={() => handleGenerate('code')}
                  disabled={isGenerating}
                  className="w-full mt-2 bg-yellow-500 hover:bg-yellow-600 text-black"
                >
                  {isGenerating ? 'Grok Modifying...' : 'Modify Code'}
                </Button>
              </div>
            </TabsContent>
            
            <TabsContent value="self" className="space-y-3">
              <div>
                <label className="text-sm text-gray-400 mb-2 block">Self-Analysis</label>
                <p className="text-xs text-gray-500 mb-2">
                  Grok will analyze and suggest improvements
                </p>
                <Button
                  onClick={() => handleGenerate('self-modify')}
                  disabled={isGenerating}
                  className="w-full bg-gradient-to-r from-purple-500 to-cyan-500 hover:from-purple-600 hover:to-cyan-600 text-white"
                >
                  {isGenerating ? 'Grok Analyzing...' : 'Analyze System'}
                </Button>
              </div>
            </TabsContent>
          </Tabs>
          
          {lastResponse && (
            <div className="mt-4 p-3 bg-gray-800 rounded-lg">
              <div className="text-xs text-gray-400 mb-1">Grok Response:</div>
              <div className="text-sm text-green-400">
                {lastResponse.success ? '✓ Success' : '✗ Failed'}
              </div>
              {lastResponse.metadata && (
                <div className="text-xs text-gray-500 mt-1 max-h-20 overflow-y-auto">
                  {JSON.stringify(lastResponse.metadata, null, 2)}
                </div>
              )}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
